apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  type: LoadBalancer
  selector:
    app: helloworldapp
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-deployment-rolling-update
  labels:
    app: helloworldapp
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: helloworldapp
  template:
    metadata:
      labels:
        app: helloworldapp
        role: rolling-update
    spec:
      containers:
      - name: helloworldapp
        image: $(dockerImage):$(BUILD_NUMBER)
        ports:
        - containerPort: 8000